name: build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure (CMake)
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build (Release)
        run: cmake --build build --config Release --parallel

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SwitchPrimaryMonitor-Release-win64
          path: |
            build/Release/SwitchPrimaryMonitor.exe

      - name: Package ZIP (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $version = "$env:GITHUB_REF_NAME"
          New-Item -ItemType Directory -Path out -Force | Out-Null
          Copy-Item build/Release/SwitchPrimaryMonitor.exe out/
          Copy-Item README.md out/
          $zip = "SwitchPrimaryMonitor-$version-win64.zip"
          Compress-Archive -Path out/* -DestinationPath $zip -Force
          Write-Host "Created $zip"

      - name: Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            SwitchPrimaryMonitor-*-win64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

